### ISSUE TITLE
Is there scope for adding bezier curves and circular arcs?

### ISSUE THREAD

**Issue by ornamentist** [lycantropos/rene#4]
Thank you for a very well constructed and useful library!

Would there be scope for adding support for non-linear geometry like Bezier curves or circles and circular arcs?  Or would that not be compatible with this style of library?

**Comment by lycantropos** [comment]
Hi, thanks for the feedback,
about non-linear geometries: it will be great to have them, but I'm not aware of algorithms for circle-polygon intersection and others, so if you know one -- then we can try to implement it.

**Comment by ornamentist** [comment]
I need to do more research on algorithms for the various linear/non-linear interactions and revisit this after that.

**Comment by lycantropos** [comment]
good luck in your research, I hope it will be productive
